WHITE = "#FFFFFF"
RED = "#F87171"
GREEN = "#4ADE80"
LIGHT_GREEN = "#3AFD50"
ORANGE = "#FBBF24"
LIGHT_GRAY = "#94A3B8"
BLUE = "#60A5FA"
DARK_NAVY = "#0F172A"
DARK_BLUE = "#1E293B"
DARK_BLUE_GRAY = "#334155"
DARK_PURPLE = "#3B2A33"

PRIMARY_BG = DARK_BLUE
SECONDARY_BG = DARK_BLUE_GRAY
DARK_BLUE_BG = DARK_NAVY
WHITE_BG = WHITE
GREEN_BG = GREEN
RED_BG = RED
BANNED_BG = DARK_PURPLE

PRIMARY_FG = WHITE
MUTED_FG = LIGHT_GRAY
DARK_FG = DARK_NAVY
STATUS_SUCCESS = GREEN
STATUS_WARNING = ORANGE
STATUS_ERROR = RED
STATUS_RETURNED = BLUE

ACTIVE_TAB_BG = GREEN
ACTIVE_TAB_FG = DARK_FG
INACTIVE_TAB_BG = SECONDARY_BG
INACTIVE_TAB_FG = PRIMARY_FG