WINDOW_WIDTH = 850
WINDOW_HEIGHT = 680

DASHBOARD_WINDOW_WIDTH = 1500
DASHBOARD_WINDOW_HEIGHT = 800

BTN_FONT = ("Arial", 18)
BTN_WIDTH = 12
BTN_CURSOR = "hand2"

ITEMS_PER_PAGE = 5
GRID_ITEMS_PER_PAGE = 9
NOTIFICATIONS_PER_PAGE = 7
USER_PER_PAGE = 15

RESERVATION_COLUMNS = 3
ROWS_PER_PAGE = 3
RESERVATION_ITEMS_PER_PAGE = RESERVATION_COLUMNS * ROWS_PER_PAGE

USER_COLUMN = 5

DEPT_CATE_WIDTH = 320
DEPT_CATE_HEIGHT = 160

MAX_CHIPS = 2
CELL_HEIGHT = 80

POPUP_COLUMNS = 5
POPUP_ROWS = 4
POPUP_PER_PAGE = POPUP_COLUMNS * POPUP_ROWS
POPUP_CARD_WIDTH = 220
POPUP_CARD_HEIGHT = 125